paurakh/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home, name = 'home'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('paurakh.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paurakh/models.py
from django.db import models

# Create your models here.

#This model for the home page

    
class Home(models.Model):
    fullName= models.CharField(max_length=20)
    greetingOne = models.CharField(max_length=5)
    greetingTwo = models.CharField(max_length=5)
    photo = models.ImageField(upload_to='photos/') 
    
    #It will modified when it saved
    updated = models.DateTimeField(auto_now=True)
    
    def __str__(self):
       return self.fullName
   
   # about page of my self
class About(models.Model):
    title = models.CharField(max_length=50)
    position = models.CharField(max_length=100)
    description = models.TextField(blank=False)
    photo = models.ImageField(upload_to='photos/')
     #It will modified when it saved
    updated = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.position
    
class Profile(models.Model):
    about = models.ForeignKey(About, on_delete=models.CASCADE)
    socialMedia = models.CharField(max_length=10)
    link = models.URLField(max_length=200)
    
#skill portion
class Category(models.Model):
    name = models.CharField(max_length=20)

    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Skill'
        verbose_name_plural = 'Skills'

    def __str__(self):
        return self.name

class Skills(models.Model):
    category = models.ForeignKey(Category,
                                on_delete=models.CASCADE)
    skill_name = models.CharField(max_length=20)
    
class Portfolio(models.Model):
    image = models.ImageField(upload_to='portfolio/')
    link = models.URLField(max_length=200)
    def __str__(self):
        return f'Portfolio{self.id}'

paurakh/views.py
from django.shortcuts import render
from .models import *

# Create your views here.
def home(request):
    
    # nav section 
 
    #home Section
    home = Home.objects.latest('updated')
    

    #about
    about = About.objects.latest('updated')
    Profiles = Profile.objects.filter(about = about)
    
    #skills
    categories = Category.objects.all()
    
    #Profolio
    portfolios = Portfolio.objects.all()
    
    
    context = {

        'home': home,
        'about':about,
        'Profiles':Profiles,
        'categories':categories,
        'portfolios':portfolios,
        
    }
    return render(request,'index.html',context)

templates/index.html
{%load static%}
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- ===== CSS ===== -->
        <link rel="stylesheet" href="{%static 'assets/css/styles.css'%}">

        <!-- ===== BOX ICONS ===== -->
        <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>

        <title>Paurakh Saud</title>
        <link rel="icon" type="image/x-icon" href="{%static 'assets/img/tablogo.png'%}">
    </head>
    <body>
        <!--===== HEADER =====-->
        <header class="l-header" style="background-color: #7be3c4;">
            <nav class="nav bd-grid">
                <div>
                    <img src="{%static 'assets/img/mylogo.png'%}" width="180px" alt="My Logo">
                </div>
                <div class="nav__menu" id="nav-menu">
                    <ul class="nav__list">
                        <li class="nav__item"><a href="#home" class="nav__link active">Home</a></li>
                        <li class="nav__item"><a href="#about" class="nav__link">About</a></li>
                        <li class="nav__item"><a href="#skills" class="nav__link">Skills</a></li>
                        <li class="nav__item"><a href="#portfolio" class="nav__link">Portfolio</a></li>
                        <li class="nav__item"><a href="#contact" class="nav__link">Contact</a></li>
                    </ul>
                </div>

                <div class="nav__toggle" id="nav-toggle">
                    <i class='bx bx-menu'></i>
                </div>
            </nav>
        </header>

        <main class="l-main">
            <!--===== HOME =====-->
            <section class="home" id="home" style="background-color: #7be3c4;">
                <div class="home__container bd-grid">
                    <h1 class="home__title"><span>{{home.greetingOne}}</span><br>{{home.greetingTwo}}</h1>
                     


                    <div class="home__scroll">
                        <a href="#about" class="home__scroll-link" style="color: rgb(58, 57, 57);"><i class='bx bx-up-arrow-alt' ></i>Scroll down</a>
                    </div>

                    <img src="{{home.photo.url}}"  alt="" class="home__img">
                </div>
            </section>
            
            <!--===== ABOUT =====-->
            <section class="about section" id="about">
                <h2 class="section-title">About</h2>

                <div class="about__container bd-grid">
                    <div class="about__img" style="background-color: #7be3c4;">
                        <img src="{{about.photo.url}}" style="height:auto; width:auto; margin-top:-20px" >
                    </div>

                    <div>
                        <h2 style="color: #7be3c4;" class="about__subtitle">{{ about.title }}</h2>
                        <span style="text-decoration: underline;" class="about__profession">{{about.position}}</span>
                        <p class="about__text" style="text-align: justify;">{{about.description}}</p>

                        <div class="about__social">
                            <a href="https://www.linkedin.com/in/paurakh-saud-17b4021a3/" target="_blank" class="about__social-icon"><i class='bx bxl-linkedin'></i></a>
                            <a href="https://github.com/devpaurakh" class="about__social-icon" target="_blank"><i class='bx bxl-github'></i></a>
                            <a href="https://twitter.com/_itsmeace01" target="_blank" class="about__social-icon"><i class='bx bxl-twitter'></i></a>
                        </div>
                    </div>
                </div>
            </section>

            <!--===== SKILLS =====-->
            <section class="skills section" id="skills">
                <h2 class="section-title">Skills</h2>

                <div class="skills__container bd-grid">
                    <div class="skills__box">
                        {% for category in categories %}
                            <h3 class="skills__subtitle" style="color: #7be3c4;">{{ category.name }}</h3>
                            {% for skills in category.skills_set.all %}
                                <span class="skills__name" style="cursor: pointer;">{{ skills.skill_name }}</span>
                            {% endfor %}
                        {% endfor %} 
                    </div>
                    

                    <div class="skills__img">
                        <img src="{%static 'assets/img/skill.jpeg'%}" alt="">
                    </div>
                </div>
            </section>

            <!--===== PORTFOLIO =====-->
            <section class="portfolio section" id="portfolio">
                <h2 class="section-title">Portfolio</h2>

                
                <div class="portfolio__container bd-grid">

                    {% for portfolio in portfolios %}
                    
                    <div class="portfolio__img">
                        <img src="{{ portfolio.image.url }}" style="height: 200px;" alt="">

                        <div class="portfolio__link">
                            <a href="{{ portfolio.link }}" class="portfolio__link-name">View details</a>
                        </div>
                    </div>

                    {% endfor %}
                    
                </div>
                
            </section>

            <!--===== CONTACT =====-->
            <section class="contact section" id="contact">
                <h2 class="section-title">Contact</h2>

                <div class="contact__container bd-grid">
                    <div class="contact__info">
                        <h3 class="contact__subtitle" style="color: #7be3c4;">EMAIL</h3>
                        <span class="contact__text">info.paurakhsaud2022@gmail.com</span>

                        <h3 class="contact__subtitle" style="color: #7be3c4;">ADRESS</h3>
                        <span class="contact__text">Kathmandu, Nepal</span>
                    </div>

                    <form action="" class="contact__form">
                        <div class="contact__inputs">
                            <input type="text" placeholder="Name" class="contact__input">
                            <input type="mail" placeholder="Email" class="contact__input">
                        </div>

                        <textarea name="" id="" cols="0" rows="10" class="contact__input"></textarea>

                        <input type="submit" value="Send" class="contact__button" style="background-color: #7be3c4;">
                    </form>
                </div>
            </section>
        </main>

        <!--===== FOOTER =====-->
        <footer class="footer section">
            <div class="footer__container bd-grid">
                <div class="footer__data">
                    <h2 class="footer__title">Paurakh Saud</h2>
                    <p class="footer__text">I'm Paurakh saud and Welcome to my Webpage</p>
                </div>

                <div class="footer__data">
                    <h2 class="footer__title">EXPLORE</h2>
                    <ul>
                        <li><a href="#home" class="footer__link">Home</a></li>
                        <li><a href="#about" class="footer__link">About</a></li>
                        <li><a href="#skills" class="footer__link">Skills</a></li>
                        <li><a href="#portfolio" class="footer__link">Portfolio</a></li>
                        <li><a href="#Contact" class="footer__link">Contact</a></li>
                    </ul>
                </div>
                
                <div class="footer__data">
                    <h2 class="footer__title">FOLLOW</h2>
                    <a href="#" class="footer__social"><i class='bx bxl-facebook' ></i></a>
                    <a href="#" class="footer__social"><i class='bx bxl-instagram' ></i></a>
                    <a href="#" class="footer__social"><i class='bx bxl-twitter' ></i></a>
                </div>


            </div>
        </footer>

        <!--===== SCROLL REVEAL =====-->
        <script src="https://unpkg.com/scrollreveal"></script>

        <!--===== MAIN JS =====-->
        <script src="{%static 'assets/js/main.js'%}"></script>
    </body>
</html>